"""Add DecisionSnapshot table and current_decision_id to Application

Revision ID: 60d98ca7f5b2
Revises: 731d8db58d5e
Create Date: 2026-07-15 23:38:12.455374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d98ca7f5b2'
down_revision: Union[str, Sequence[str], None] = '731d8db58d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('composite_score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('interview_probability', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('risk', sa.String(), nullable=False),
    sa.Column('effort_minutes', sa.Integer(), nullable=False),
    sa.Column('canonical_role', sa.String(), nullable=True),
    sa.Column('role_confidence', sa.Float(), nullable=True),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('retriever_version', sa.String(), nullable=True),
    sa.Column('ranker_version', sa.String(), nullable=True),
    sa.Column('registry_version', sa.String(), nullable=True),
    sa.Column('skill_graph_version', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_snapshots_application_id'), 'decision_snapshots', ['application_id'], unique=False)
    op.create_index(op.f('ix_decision_snapshots_generated_at'), 'decision_snapshots', ['generated_at'], unique=False)
    op.add_column('applications', sa.Column('current_decision_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_applications_current_decision_id'), 'applications', ['current_decision_id'], unique=False)
    op.create_index(op.f('ix_applications_tier'), 'applications', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_tier'), table_name='applications')
    op.drop_index(op.f('ix_applications_current_decision_id'), table_name='applications')
    op.drop_column('applications', 'current_decision_id')
    op.drop_index(op.f('ix_decision_snapshots_generated_at'), table_name='decision_snapshots')
    op.drop_index(op.f('ix_decision_snapshots_application_id'), table_name='decision_snapshots')
    op.drop_table('decision_snapshots')
    # ### end Alembic commands ###
