"""add_company_registry

Revision ID: 731d8db58d5e
Revises: 3b9c5d6e7f8a
Create Date: 2026-07-15 21:20:55.234532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731d8db58d5e'
down_revision: Union[str, Sequence[str], None] = '3b9c5d6e7f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_category', sa.String(), nullable=False),
    sa.Column('secondary_categories', sa.JSON(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('offices', sa.JSON(), nullable=True),
    sa.Column('hiring_regions', sa.JSON(), nullable=True),
    sa.Column('ats', sa.JSON(), nullable=True),
    sa.Column('careers_url', sa.String(), nullable=True),
    sa.Column('job_listing_url', sa.String(), nullable=True),
    sa.Column('fresher_friendly', sa.Boolean(), nullable=True),
    sa.Column('internship', sa.Boolean(), nullable=True),
    sa.Column('remote_policy', sa.String(), nullable=True),
    sa.Column('backend_stack', sa.JSON(), nullable=True),
    sa.Column('hiring_patterns', sa.JSON(), nullable=True),
    sa.Column('interview_difficulty', sa.Integer(), nullable=True),
    sa.Column('interview_oa', sa.Boolean(), nullable=True),
    sa.Column('interview_system_design', sa.Boolean(), nullable=True),
    sa.Column('salary_fresher_min', sa.Float(), nullable=True),
    sa.Column('salary_fresher_max', sa.Float(), nullable=True),
    sa.Column('salary_intern_min', sa.Float(), nullable=True),
    sa.Column('salary_intern_max', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_primary_category'), 'companies', ['primary_category'], unique=False)
    op.create_table('company_aliases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_aliases_alias'), 'company_aliases', ['alias'], unique=False)
    op.create_index(op.f('ix_company_aliases_company_id'), 'company_aliases', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_aliases_company_id'), table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_alias'), table_name='company_aliases')
    op.drop_table('company_aliases')
    op.drop_index(op.f('ix_companies_primary_category'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
